sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json

# docker run -it -v $(pwd):/app ruby sh
# gem install travis
# travis login --github-token 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 --com
# travis encrypt-file service-account.json -r HoonHenry/multi-k8s --com